### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by flypie** [ricaflops/Jupiter-II#1]
Hi,
I had a look at your Ace and it looks very good. I'm doing a similar project I did find that I had to boost the composite sign before I could get a monitor to sync I used this circuit. https://jupiter-ace.co.uk/hardware_ebvdoboard.html I'm thinking of doing the similar for the audio out rather than use a speaker, not sure of what needed to get impedance correct.

**Comment by ricaflops** [comment]
Hi,Thank You for the message.
I'm still waiting for the PCB to arrive from JLCPCB. It should take another month or two due to the current mail delays from China. Then I'll have several hours of fun validating those CUPL codes and making it work!

I did some protoboarding and tested the video circuit with a studio grade SONY video monitor and it worked fine. Should have experimented with a regular TV/monitor also before ordering the PCB. Thanks for the advice.

This project is intended to be a base for experimenting on Jupiter Ace expansions. I have some ideas to try and the type of expansion connectors chosen and the inclusion of more video signals shall make it easier to experiment on protoboard.
Many years ago I build a Jupiter Ace using wire-wrapping. You can check the actual pictures of it on the Jupiter Ace resource site. It was ugly but worked. Now that I'm reviving interest on this computer it is a good time to build it more adequately.
Just saw your Ace-2019 project in Github. Great work!
I specially like the use of dual port RAMs in video circuit.

Best regards,Ricardo.


    Em quarta-feira, 29 de abril de 2020 14:01:12 BRT, flypie <notifications@github.com> escreveu:  
 
 


Hi,
I had a look at your Ace and it looks very good. I'm doing a similar project I did find that I had to boost the composite sign before I could get a monitor to sync I used this circuit. https://jupiter-ace.co.uk/hardware_ebvdoboard.html I'm thinking of doing the similar for the audio out rather than use a speaker, not sure of what needed to get impedance correct.

**Comment by flypie** [comment]
Hi

I order some SRAM from Wuhan earlier January, got it last week. I'm using the dual-port so that I don't have to use multiples of the video speed for the CPU.  There is the possibility with the faster Z80s to bypass the dived by 2 on the CPU and use the raw clock. With a few mods it should be possible to double the crystal and then dive by 2 for the video. The ACE3NOKB version I'm starting testing today will allow me to play with this using jumpers.
Your use of the 74HCT4040 is great I think I will do the same.
Are you going to stick with the DIP Z80? I've decided to use QFP for the CPU and ROM to save space and put 64k of RAM on the board using 2  IS61C256AL-12JLI.

**Comment by ricaflops** [comment]
Hi,My option on vintage components (DIP Z80,ROM,RAM,etc) was to reuse as much components from my old inventary as I can, and keep costs low. The use of those old GALs was also motivated to easy the PCB design.

At this moment I want a working and compatible Jupiter Ace to experiment on interfacing ..and allow some nostalgic experience running those games on a real hardware as well.

I specifically want to experiment on sound with AY-3-8910, an UART to load/save via USB/RS232, color video, and test some ideas on memory paging and extended vocabulary ROM. Perhaps approaching something like an imaginary ZX-Spectrum competitor or what would be a backward compatible second generation Ace at that time. An Ace-Rainbow or Jupiter-Colour?

The clever approach in your project of freeing the video RAM from CPU syncing makes it possible I think to easily generate a VGA or HDMI video signal and use modern monitors. And perhaps even enable higher resolution video by increasing video RAM size and some changes in the original ROM code.
Your project is very inspiring for me and there is a lot to learn from it. Keep the nice work.

-RL
    Em quinta-feira, 30 de abril de 2020 10:11:15 BRT, flypie <notifications@github.com> escreveu:  
 
 


Hi

I order some SRAM from Wuhan earlier January, got it last week. I'm using the dual-port so that I don't have to use multiples of the video speed for the CPU. There is the possibility with the faster Z80s to bypass the dived by 2 on the CPU and use the raw clock. With a few mods it should be possible to double the crystal and then dive by 2 for the video. The ACE3NOKB version I'm starting testing today will allow me to play with this using jumpers.
Your use of the 74HCT4040 is great I think I will do the same.
Are you going to stick with the DIP Z80? I've decided to use QFP for the CPU and ROM to save space and put 64k of RAM on the board using 2 IS61C256AL-12JLI.

**Comment by flypie** [comment]
Hi

The recreating the ace is what I did first to make sure that I know how it all worked.

It is worth looking at the Z180 as it has an MMU inboard and it is still made by Zilog it would mean ROM changes to handle the interrupts. But with a 1Meg address space placing a 64k for VGA will out of the base 64k and paging the sections in to write to them would make sense. It would also mean that it might be possible to reduce the CPU VDG conflict. The original design for Colour was [this](http://www.jupiter-ace.co.uk/hardware_colour_board.html)

For other expansion, it might be worth looking at[ PCMIA/Compact flash](https://en.wikipedia.org/wiki/PC_Card). It uses 5v TTL levels. Someone has done some work on [this ](https://z80project.wordpress.com/2015/07/06/z80-8-bit-compact-flash-card-interface-part-1/).

I'm beginning to think the best place for any ROM expansion is the top 8K to avoid having to rewrite the tape loader.

Are you aware of [SymbOS](https://en.wikipedia.org/wiki/SymbOS) The base hardware requirements might be a good target point?

I'm glad you find the project useful it was my hope to make it easier to design and build their own machines from readily available components.

**Comment by ricaflops** [comment]
Thanks for the suggestions on Z180. will read the docs.

I agree on the ROM expansion position at the highest addresses.Lower addresses shall be RAM for the user FORTH dictionary to grown into and to keep some compatibility with the original Ace.

I am planning for the following memory organization for a 128K RAM + 16K ROM expansion:
(ASCII diagram follows)

       pg0   pg1   pg2   pg3  
    -|-----|-----|-----|-----|
FFFF | 16K |     |     |     |
C000 | ROM | 32K | 32K | 32K |
    -+-----| RAM | RAM | RAM |
BFFF | 16K | pg1 | pg2 | pg3 |
8000 | RAM |     |     |     |
    -+-----+-----+-----+-----|
7FFF |        Fixed          |
4000 |       16K RAM         |
    -+-----------------------|
3FFF |   (unexpanded Ace)    |
0000 |_______________________|

That gives a good fixed 16K RAM (non-paged) contiguous space for the user FORTH dictionary, a page of 16K RAM + 16K ROM, and more 3 pages of 32K RAM.

The plan is use the available two 8-bit I/O ports of AY-3-8910 sound generator for memory paging and screen colour register.
Port A: Screen colour INK/PAPER registers (4-bit each)
Port B: Memory paging (2-bits), Screen paging (1-bit), Charset page (1-bit), (remaining 4-bit to be defined yet)

Never looked at SymbOS before. I will check that.

About the audio output impedance. I never thinked too much on that.. lazy of me! 
But I can remedy that.

The Wikipedia https://en.wikipedia.org/wiki/Line_level states that a typical consumer audio equipment line input impedance is around 10k ohms and the nominal amplitude is 0.89Vpp full range.

TTL LS family output impedance can be estimated around 100 ohm or so.
That allow us to reduce the TTL 5Vpp to a compatible 0.88Vpp using a 4.7K+1k voltage divider without a hard load on TTL. 

A decoupling capacitor in series is needed as a high-pass filter to block DC current.
That filter cut-off frequency (-3dB point) is: f = 1/(2*pi*R*C).
Lets choose that frequency to at least 2Hz. That is one decade below the average hearing threshold of 20Hz.
Assuming the 10K ohm as the line input impedance: C = 1/(2*pi*10k*2) = 7.96uF (minimum)
I will choose 10uF.(ASCII diagram follows)
                        10uF
From TTL----[4.7k]---+---|(---- to Audio amplifier
                     |  +
     GND----[ 1k ]---+

Just did a lab test with a function generator and a small amplifier. Worked fine with a nice flat response from 10Hz and above.
May increase that 4.7k resistor to reduce volume. Maybe a 6.8k would result in a softer audio.

The EAR and MIC circuits also deserves better attention as it was originally designed to work with very different audio lines. Working on that too.


    Em domingo, 3 de maio de 2020 10:48:36 BRT, flypie <notifications@github.com> escreveu:  
 
 


Hi

The recreating the ace is what I did first to make sure that I know how it all worked.

It is worth looking at the Z180 as it has an MMU inboard and it is still made by Zilog it would mean ROM changes to handle the interrupts. But with a 1Meg address space placing a 64k for VGA will out of the base 64k and paging the sections in to write to them would make sense. It would also mean that it might be possible to reduce the CPU VDG conflict.

For other expansion, it might be worth looking at PCMIA/Compact flash. It uses 5v TTL levels. Someone has done some work on this .

I'm beginning to think the best place for any ROM expansion is the top 8K to avoid having to rewrite the tape loader.

Are you aware of SymbOS The base hardware requirements might be a good target point?

I'm glad you find the project useful it was my hope to make it easier to design and build their own machines from readily available components.

**Comment by flypie** [comment]
Hi

Thanks for the audio info, I do not get on with analogue.

Someone has done this. The ROM model is good and I the Video Model, only using one dual-port RAM is a lot cheaper.

https://www.tindie.com/products/tynemouthsw/minstrel-4th-z80-computer-kit/

**Comment by ricaflops** [comment]
Board was received two days ago and hardware were tested/debugged.
Updated circuit uploaded. It includes some important corrections and a better/robust video output.
Thanks for the suggestion.And yes, that tynemouthsw product is very well thought. I like that they kept software compatibility.

    Em segunda-feira, 4 de maio de 2020 18:30:57 BRT, flypie <notifications@github.com> escreveu:  
 
 


Hi

Thanks for the audio info, I do not get on with analogue.

Someone has done this. The ROM model is good and I the Video Model, only using one dual-port RAM is a lot cheaper.

https://www.tindie.com/products/tynemouthsw/minstrel-4th-z80-computer-kit/

**Comment by flypie** [comment]
Hi,
Good to hear.

    On Monday, 11 May 2020, 03:42:57 BST, Ricardo Fernandes Lopes <notifications@github.com> wrote:  
 
 

 
Board was received two days ago and hardware were tested/debugged.
Updated circuit uploaded. It includes some important corrections and a better/robust video output.
Thanks for the suggestion.And yes, that tynemouthsw product is very well thought. I like that they kept software compatibility.

 Em segunda-feira, 4 de maio de 2020 18:30:57 BRT, flypie <notifications@github.com> escreveu: 
 
 


Hi

Thanks for the audio info, I do not get on with analogue.

Someone has done this. The ROM model is good and I the Video Model, only using one dual-port RAM is a lot cheaper.

https://www.tindie.com/products/tynemouthsw/minstrel-4th-z80-computer-kit/
